<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1595985279036' stop='1595985279665'>
    <name>My Login application</name>
    <title>My Login application</title>
    <test-cases>
        <test-case start='1595985279037' status='broken' stop='1595985279664'>
            <name>should login with valid credentials</name>
            <title>should login with valid credentials</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='firefox-19.5.0'/>
            </parameters>
            <steps>
                <step start='1595985279046' status='broken' stop='1595985279664'>
                    <name>POST /session/:sessionId/url</name>
                    <title>POST /session/:sessionId/url</title>
                    <attachments>
                        <attachment title='Request' source='6ea44c5a-dafc-4b3e-b1f2-154619b95d45-attachment.json' type='application/json' size='35'/>
                    </attachments>
                    <steps>
                        <step start='1595985279397' status='passed' stop='1595985279659'>
                            <name>GET /session/:sessionId/screenshot</name>
                            <title>GET /session/:sessionId/screenshot</title>
                            <attachments>
                                <attachment title='Screenshot' source='735abc17-5198-41bc-a647-1c76b98ce35d-attachment.png' type='image/png' size='125897'/>
                            </attachments>
                            <steps/>
                        </step>
                    </steps>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Reached error page: about:neterror?e=dnsNotFound&amp;u=http%3A//qa.aem.cloud/&amp;c=UTF-8&amp;d=We%20can%E2%80%99t%20connect%20to%20the%20server%20at%20qa.aem.cloud.</message>
                <stack-trace>unknown error: Reached error page: about:neterror?e=dnsNotFound&amp;u=http%3A//qa.aem.cloud/&amp;c=UTF-8&amp;d=We%20can%E2%80%99t%20connect%20to%20the%20server%20at%20qa.aem.cloud.
                    at LoginPage.open (/Users/pjcalvo/Documents/ucreativa/automation/funda_02/TechGroundQA02/semana2dia1/test/pageobjects/page.js:11:24)
                    at LoginPage.open (/Users/pjcalvo/Documents/ucreativa/automation/funda_02/TechGroundQA02/semana2dia1/test/pageobjects/login.page.js:28:22)
                    at Context.it (/Users/pjcalvo/Documents/ucreativa/automation/funda_02/TechGroundQA02/semana2dia1/test/specs/example.e2e.js:7:19)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>